// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package recommendation_service

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation(in *jlexer.Lexer, out *RecommendedBySponsoredProductsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if !in.IsDelim(']') {
			*out = make(RecommendedBySponsoredProductsResponse, 0, 1)
		} else {
			*out = RecommendedBySponsoredProductsResponse{}
		}
		for !in.IsDelim(']') {
			var v1 RecommendationBySponsoredProducts
			easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation1(in, &v1)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation(out *jwriter.Writer, in RecommendedBySponsoredProductsResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation1(out, v3)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v RecommendedBySponsoredProductsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecommendedBySponsoredProductsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecommendedBySponsoredProductsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecommendedBySponsoredProductsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation(l, v)
}
func easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation1(in *jlexer.Lexer, out *RecommendationBySponsoredProducts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "placement_name":
			out.Placement = string(in.String())
		case "strat_message":
			out.Heading = string(in.String())
		case "recs":
			if in.IsNull() {
				in.Skip()
				out.Products = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Products = make([]ProductByBySponsoredProducts, 0, 1)
				} else {
					out.Products = []ProductByBySponsoredProducts{}
				}
				for !in.IsDelim(']') {
					var v4 ProductByBySponsoredProducts
					easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation2(in, &v4)
					out.Products = append(out.Products, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation1(out *jwriter.Writer, in RecommendationBySponsoredProducts) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"placement_name\":")
	out.String(string(in.Placement))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"strat_message\":")
	out.String(string(in.Heading))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"recs\":")
	if in.Products == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in.Products {
			if v5 > 0 {
				out.RawByte(',')
			}
			easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation2(out, v6)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjson95d8ed55DecodeMobileSearchApiSrvRecommendation2(in *jlexer.Lexer, out *ProductByBySponsoredProducts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pid":
			out.SKU = string(in.String())
		case "ct_url":
			out.CtURL = string(in.String())
		case "cid":
			out.CID = string(in.String())
		case "did":
			out.DID = string(in.String())
		case "simple_sku":
			out.SimpleSKU = string(in.String())
		case "pdp_sku":
			out.PDPSKU = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson95d8ed55EncodeMobileSearchApiSrvRecommendation2(out *jwriter.Writer, in ProductByBySponsoredProducts) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"pid\":")
	out.String(string(in.SKU))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ct_url\":")
	out.String(string(in.CtURL))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"cid\":")
	out.String(string(in.CID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"did\":")
	out.String(string(in.DID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"simple_sku\":")
	out.String(string(in.SimpleSKU))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"pdp_sku\":")
	out.String(string(in.PDPSKU))
	out.RawByte('}')
}
